[General]
; How many times we should try running the game (run the script multiple times or increase this value if
; the game still doesn't run)
attempts=50
; How many milliseconds to wait between each running attempt
timeBetweenAttempts=50
; The full path to Syndicate.exe, it'll fall back to the current directory if not found
exePath="C:\Program Files (x86)\Syndicate\System\Win32_x86_Release\Syndicate.exe"
; Wait for the game process to close between each unsuccessful attempt (1 to enable). The game will take
; much longer to launch and any potential error pop-up won't be closed until after the game closes.
useRunWait=0
